version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    deploy:
      replicas: 1
    ports:
      - 9870:9870
      
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    # container_name: datanode
    restart: always
    deploy:
      replicas: 3
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    expose:
      - "2181"
    ports:
      - 2181:2181
           
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    expose:
      - "9092"
    ports:
      - 9092:9092
      - 19092:19092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:19092
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://0.0.0.0:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      JMX_PORT: 9999
  kafka_manager:
    image: hlebalbau/kafka-manager:1.3.3.18
    container_name: kafka_manager
    expose:
      - "9000"
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
      command: -Dpidfile.path=/dev/null
    links:
        - kafka
        - zookeeper
    depends_on:
        - "zookeeper"
        - "kafka"



  pyspark:
    build: .
    container_name: pyspark-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./pyspark/:/home/jovyan/work/
      - ./model/:/home/jovyan/work/model
    env_file:
      - ./hadoop.env
    restart: "no"
   
    # command: sh -c "pip install torch torchtext spacy && python -m spacy download en_core_web_md && python -m spacy link en_core_web_md en"
      
  nodejs:
    build: .
    container_name: node-js
    
    volumes:
      - ./streaming:/usr/app/streaming
      - ./streaming/node_modules:/usr/app/streaming/node_modules
    # environment: 
    #   TZ: 
    command: npm run dev
    ports: 
      - "80:8080"
    networks: 
      - app-network
    depends_on: 
      - 'kafka'
    
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:

networks:
  app-network:
    driver: bridge